name: video_player_flick
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.0
  provider: ^6.0.1
  wakelock: ^0.6.0
  universal_html: ^2.0.8
  dio: ^4.0.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
